name: Cotinous Integration
on: pull_request
jobsL
  run_code_checks:
    runs-on: ubuntu-latest
    step:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20
      - name: Run linting
        run: |
          go fmt ./..
          gi vet ./..