name: Cotinous Integration

on: [pull_request, push]

jobs:
  run_code_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
      - name: Run linting
        run: |
          go fmt ./...
          go vet ./...
      - name: Build
        run: go build -v ./...